### ISSUE TITLE
Problem simplesamlphp doesn't load

### ISSUE THREAD

**Issue by douglasilva** [sgomez/simplesamlphp-module-dbal#2]
Please, I'm need help!

When I run the command "vendor/bin /dbalschema" I get the error message PHP Fatal error: Class 'SimpleSAML\Module' not found in /var/simplesamlphp/modules/dbal/bin/dbalschema on line 18

I try the version of SimpleSAMLPHP 1.14.9, 1.14.8 and get the same error.

**Comment by bgsbox** [comment]
Replace 'SimpleSAML\Module' with 'SimpleSAML_Module' in '{simplesamlphp-base-path}/modules/dbal/bin/dbalschema'

It works for me.

**Comment by sgomez** [comment]
Sorry, this module was only available for SimpleSAMLphp master branch.

From now, you can use ^1.0 for SimpleSAMLphp 1.14 and ^2.0 for master branch.

Please, see the [README.md](https://github.com/sgomez/simplesamlphp-module-dbal/blob/master/README.md) file.
