### ISSUE TITLE
Error title_KVStore table on the datastore is missing.

### ISSUE THREAD

**Issue by Abhishek103** [sgomez/simplesamlphp-module-dbal#3]
Hi, 
it's more of a question I used this dbal module for oauth2 implementation, Now I was able to implement successfully on my local system.
Now when I shifted the folder to server I got this error,

> title_KVStore table on the datastore is missing. Did you create the schema? See README.md from dbal module for more information.})

My question is how should I run this bash$ vendor/bin/dbalschema to create the schema on server ??
Please help,
Can this be solved by creating the hook_dbal file ?
P.S I uploaded the db on my server with all required changes.

**Comment by Abhishek103** [comment]
hi, 
I tried a workaround by linking my desktop application via server database and running the  bash$ vendor/bin/dbalschema, and it worked 
is the the rightway or it should be done another way ?
Thanks

**Comment by sgomez** [comment]
Whenever you have installed the same module version it is indifferent if you run the `dbalschema` script as long as you use the same database schema.

Both ways are correct.
