### ISSUE TITLE
Using other Databasedriver e.g. SQLite

### ISSUE THREAD

**Issue by grueneedv** [sgomez/simplesamlphp-module-dbal#4]
I'm trying to setup a SQLite database as described here:
http://doctrine-dbal.readthedocs.io/en/latest/reference/configuration.html

At the config file config/module_dbal.php:
'store.dbal.url' => 'sqlite:////usr/local/var/db.sqlite',
'store.dbal.dbname' => 'dummy',
but the command vendor/bin/dbalschema complains because of the missing driver. Adding that to the config, the dbschema is aparrently created but in fact nothing is in the database.

So the question is, does this module work with any other database than mysql and if so how to setup?

**Comment by sgomez** [comment]
Yes, this is a design issue. I'm going to change it to use a database url too (for BC). Wait for it.

**Comment by sgomez** [comment]
Now the URL database (`'store.dbal.url' => '...'`) is the recommended way to configure the database. Tested with sqlite.



Branches 1.0.x (811c919ea765d5d787994c3655c4962ab8020974) and 2.0.x  (ca53774e30beac7f4a6163f0d23793f1acfb529d) are updated. Can you update your dependencies?

**Comment by grueneedv** [comment]
Seems to work for me now, Thanks.
