### ISSUE TITLE
Private informations in exception

### ISSUE THREAD

**Issue by Elektordi** [sgomez/simplesamlphp-module-dbal#8]
Hello,

Using `print_r($e);` in exception handling is a security problem, since the whole world can read it, and access private information in calls parameters.

You should use the integrated error reporter of simplesamlphp, which is pretty good at logging, or if you really need to display such stuff in your module, you should only do this if DEBUG is TRUE in global configuration.

**Comment by sgomez** [comment]
Sorry, I don't use that. All errors are handled with SSP exceptions. Can you be more specific? Thanks.

**Comment by Elektordi** [comment]
Oh sorry, I just  realize I opened the issue on the wrong repo :(
It was meant for simplesamlphp-module-oauth2, I'll move the issue there...
